### ISSUE TITLE
Velocity Tracker doesn't account for play space velocity (unlike tutorial version)

### ISSUE THREAD

**Issue by SmartCarrion** [ExtendRealityLtd/Tilia.SDK.OculusIntegration.Unity#13]
The OVRAnchorVelocityEstimator.cs looks like an older version of the script as it does not account for playspace velocity as is done in the tutorial version, see https://github.com/ExtendRealityLtd/VRTK.Tutorials.OculusIntegration/commit/135e8017e82ca20d0a8b3edf712faed39b255c0f

**Comment by extendreality** [comment]
Fixed with https://github.com/ExtendRealityLtd/Tilia.SDK.OculusIntegration.Unity/pull/16
