### ISSUE TITLE
Some property drawers are not drawn in the Unity Inspector

### ISSUE THREAD

**Issue by Wolar** [ExtendRealityLtd/Tilia.SDK.OculusIntegration.Unity#2]
I have integrated this package via Package Manager, I also use VRTK.Prefabs (see screenshot for packages list). 

But if I use any of the scripts / prefabs from this repository, properties like Controller or Button are not drawn in the Unity Inspector which I think should be (for example on OVRInputButtonAction, see second screenshot)

I have Odin Inspector plugin in the project, I have tried to remove it to be sure it's not cause of the problem but the issue persists.

<img width="1158" alt="Screenshot 2019-12-06 at 21 32 11" src="https://user-images.githubusercontent.com/6131648/70354770-c775a080-1870-11ea-9539-5abdb29cdce3.png">
<img width="1920" alt="Screenshot 2019-12-06 at 21 33 34" src="https://user-images.githubusercontent.com/6131648/70354771-c775a080-1870-11ea-9c40-9c1f24355ebb.png">

Am I doing something wrong or is this an issue / work in progress?

**Comment by thestonefox** [comment]
Fix https://github.com/ExtendRealityLtd/Tilia.SDK.OculusIntegration.Unity/pull/3
