### ISSUE TITLE
Error when using prefab

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.SDK.OculusIntegration.Unity#84]
### Environment

* Code version: #83 
* Platform version: Unity 2021.3.15f1
* 3rd party dependencies: Oculus Integration v50

### Steps to reproduce

using the CameraRigs.OculusIntegration Prefab

### Current behavior

NullReferenceException: Object reference not set to an instance of an object
Tilia.SDK.OculusIntegration.Tracking.CameraRig.OVRPluginDetailsRecord.OnEnable () (at Library/PackageCache/io.extendreality.tilia.sdk.oculusintegration.unity@2.1.2/Runtime/SharedResources/Scripts/Tracking/CameraRig/OVRPluginDetailsRecord.cs:58)

That line is
`            passthroughLayer.hidden = PassthroughLayerHiddenOnEnable;`

![image](https://user-images.githubusercontent.com/22952143/226262914-60997e0d-f38f-44d5-a099-cd2818c71b6f.png)
there is no OVRPassthroughLayer on the ovr camera rig by default and our script didn't do a null check

**Comment by fight4dream** [comment]
the OVR Passthrough Layer setup is optional, so we better provide null checking
https://developer.oculus.com/documentation/unity/unity-passthrough/#create-passthrough-layer
also notice that we can add multiple of the passthrough layers (up to 3 instances can be active at any given time)
so i urge to review the logic of this portion whether it is needed to expand the variable into a list

**Comment by thestonefox** [comment]
yeah using a list may be a better idea

**Comment by thestonefox** [comment]
fixed https://github.com/ExtendRealityLtd/Tilia.SDK.OculusIntegration.Unity/pull/86

**Comment by thestonefox** [comment]
oh actually i need to do the list thing too

**Comment by thestonefox** [comment]
Here's the multiple lists, I just need to test it on the headset.
https://github.com/ExtendRealityLtd/Tilia.SDK.OculusIntegration.Unity/pull/87
